apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ravinder-autopod
  name: ravinder-autopod
spec:
  containers:
  - image: docker.io/bitgallon/ravinder-customer:v1
    name: ravinder-autopod
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
