apiVersion: v1 # i am sending data to  v1 version of k8s control plane 
kind: Pod 
metadata:
  name: ravinder-pod-v1 # name of pod i want to request 
spec:
  containers: 
  - name: ravinder-v1 # name of container 
    image: docker.io/bitgallon/ravinder-customer:v1 # image from docker hub 
    ports:
    - containerPort: 80 #internal container port 