apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ravinder-pod
  name: ravinder-pod
spec:
  containers:
  - command:
    - sleep
    - "10000"
    image: ubuntu
    name: ravinder-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
