apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ravinder-springapp
  name: ravinder-np
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ravinder-springapp
  type: NodePort
status:
  loadBalancer: {}
